version: '3.9'

volumes:
  db-volume:

networks:
  my-network:
    driver: bridge

# https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-vars:
  - &db ${COMPOSE_PROJECT_NAME}_db

services:
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Database ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  db:
    image: *db
    build: docker/db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - my-network
    hostname: *db
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-volume:/var/lib/postgresql/data
    restart: on-failure
