version: '3.9'

volumes:
  db-volume:

networks:
  mynet:
    driver: bridge

# https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields
x-vars:
  - &app ${COMPOSE_PROJECT_NAME}_app
  - &db ${COMPOSE_PROJECT_NAME}_db

services:
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ App ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  app:
    depends_on:
      - db
    image: *app
    build:
      context: .
      dockerfile: docker/app/dev/Dockerfile
    env_file:
      - .env
    environment:
      APP_HOST: *app
      DB_HOST: *db
      DB_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${COMPOSE_PROJECT_NAME}_db:${DB_PORT}/${DB_NAME}?schema=public
    networks:
      - mynet
    hostname: *app
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
    restart: on-failure
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Database ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  db:
    image: *db
    build: docker/db
    environment:
      PGPORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - mynet
    hostname: *db
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db-volume:/var/lib/postgresql/data
    restart: on-failure
